import type { Metadata } from "next";
import { Geist, Geist_Mono, Red_Hat_Display, Elms_Sans, Outfit } from "next/font/google";
import "./globals.css";

// Chosen Main Fonts

const redhat = Red_Hat_Display({subsets: ["latin"], variable: "--font-redhat", weight: ["300", "500", "700"]})
const elms = Elms_Sans({subsets: ["latin"], variable: "--font-elms", weight: ["100", "300", "500"]})
const outfit = Outfit({subsets: ["latin"], variable: "--font-outfit", weight: ["100", "200", "300", "500", "800"]})

// ------------------------------------------------------------------------------------------------

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
        ${redhat.variable} ${elms.variable} ${outfit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
